### ISSUE TITLE
鹅厂下载报错

### ISSUE THREAD

**Issue by slzhou8** [59799517/simple_sq_musuc_plus#7]
14:03:19.891 [threadPoolTaskExecutor-20] ERROR c.s.p.q.e.QQVipSearchEntity - [songInfoToMusic,42] - QQVIP歌曲信息转换失败：{"start_ts":1723730599869,"traceid":"6efb97eba3d86a83","code":0,"ts":1723730599873,"songinfo":{"code":404,"data":{"extras":{"transname":"","subtitle":"","name":"","wikiurl":"","from":""},"track_info":{"modify_stamp":0,"singer":[],"mid":"","fnote":0,"language":0,"type":0,"title":"","tid":0,"sa":0,"trace":"","file":{"hires_sample":0,"size_new":[],"size_320mp3":0,"hires_bitdepth":0,"size_96aac":0,"size_dts":0,"try_end":0,"size_360ra":[],"e_30s":0,"size_24aac":0,"size_48aac":0,"b_30s":0,"try_begin":0,"url":"","size_192aac":0,"size_128mp3":0,"size_flac":0,"media_mid":"","size_ape":0,"size_96ogg":0,"size_hires":0,"size_192ogg":0,"size_try":0,"size_dolby":0},"genre":0,"action":{"msgpay":0,"alert":0,"switch2":0,"msgid":0,"msgshare":0,"icons":0,"msgdown":0,"switch":0,"msgfav":0,"icon2":0},"ksong":{"mid":"","id":0},"index_cd":0,"id":0,"bpm":0,"isonly":0,"album":{"time_public":"","subtitle":"","name":"","mid":"","id":0,"title":"","pmid":""},"ov":0,"mv":{"vid":"","name":"","id":0,"title":"","vt":0},"pay":{"pay_play":0,"pay_status":0,"price_track":0,"time_free":0,"price_album":0,"pay_month":0,"pay_down":0},"label":"","version":0,"pingpong":"","url":"","es":"","volume":{"lra":0,"peak":0,"gain":0},"vf":[],"ppurl":"","time_public":"","vi":[],"subtitle":"","name":"","data_type":0,"interval":0,"index_album":0,"vs":[],"ktag":"","status":0},"info":{}}}}------------------------>配置：{"artistImage":"http://y.gtimg.cn/music/photo_new/T001R800x800M000#{pmid}.jpg","downloadUrl":"https://lxmusic.ikunshare.com:9763/url/tx/#{pmid}/#{brType}","albumImage":"https://y.qq.com/music/photo_new/T002R800x800M000#{pmid}.jpg","artistInfoReferer":"https://y.qq.com","searchUrl":"https://u.y.qq.com/cgi-bin/musicu.fcg","stringPlugSetName":"qq","artistInfoUrl":"https://c.y.qq.com/splcloud/fcgi-bin/fcg_get_singer_desc.fcg?singermid=#{mid}&utf8=1&outCharset=utf-8&format=xml"}
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.alibaba.fastjson.JSONArray.getJSONObject(JSONArray.java:244)
        at com.ejlchina.data.fastjson.FastjsonArray.getMapper(FastjsonArray.java:28)
        at com.sqmusicplus.plug.qqvip.entity.QQVipSearchEntity.songInfoToMusic(QQVipSearchEntity.java:40)
        at com.sqmusicplus.plug.qq.hander.QQHander.querySongById(QQHander.java:112)
        at com.sqmusicplus.plug.base.hander.SearchHanderAbstract.dnonloadAndSaveToFile(SearchHanderAbstract.java:44)
        at com.sqmusicplus.download.DownloadExcute.lambda$getDownloadInfo$0(DownloadExcute.java:90)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
14:03:19.891 [threadPoolTaskExecutor-20] ERROR c.s.p.q.e.QQVipSearchEntity - [songInfoToMusic,50] - QQVIP歌曲信息转换失败：{"start_ts":1723730599869,"traceid":"6efb97eba3d86a83","code":0,"ts":1723730599873,"songinfo":{"code":404,"data":{"extras":{"transname":"","subtitle":"","name":"","wikiurl":"","from":""},"track_info":{"modify_stamp":0,"singer":[],"mid":"","fnote":0,"language":0,"type":0,"title":"","tid":0,"sa":0,"trace":"","file":{"hires_sample":0,"size_new":[],"size_320mp3":0,"hires_bitdepth":0,"size_96aac":0,"size_dts":0,"try_end":0,"size_360ra":[],"e_30s":0,"size_24aac":0,"size_48aac":0,"b_30s":0,"try_begin":0,"url":"","size_192aac":0,"size_128mp3":0,"size_flac":0,"media_mid":"","size_ape":0,"size_96ogg":0,"size_hires":0,"size_192ogg":0,"size_try":0,"size_dolby":0},"genre":0,"action":{"msgpay":0,"alert":0,"switch2":0,"msgid":0,"msgshare":0,"icons":0,"msgdown":0,"switch":0,"msgfav":0,"icon2":0},"ksong":{"mid":"","id":0},"index_cd":0,"id":0,"bpm":0,"isonly":0,"album":{"time_public":"","subtitle":"","name":"","mid":"","id":0,"title":"","pmid":""},"ov":0,"mv":{"vid":"","name":"","id":0,"title":"","vt":0},"pay":{"pay_play":0,"pay_status":0,"price_track":0,"time_free":0,"price_album":0,"pay_month":0,"pay_down":0},"label":"","version":0,"pingpong":"","url":"","es":"","volume":{"lra":0,"peak":0,"gain":0},"vf":[],"ppurl":"","time_public":"","vi":[],"subtitle":"","name":"","data_type":0,"interval":0,"index_album":0,"vs":[],"ktag":"","status":0},"info":{}}}}------------------------>配置：{"artistImage":"http://y.gtimg.cn/music/photo_new/T001R800x800M000#{pmid}.jpg","downloadUrl":"https://lxmusic.ikunshare.com:9763/url/tx/#{pmid}/#{brType}","albumImage":"https://y.qq.com/music/photo_new/T002R800x800M000#{pmid}.jpg","artistInfoReferer":"https://y.qq.com","searchUrl":"https://u.y.qq.com/cgi-bin/musicu.fcg","stringPlugSetName":"qq","artistInfoUrl":"https://c.y.qq.com/splcloud/fcgi-bin/fcg_get_singer_desc.fcg?singermid=#{mid}&utf8=1&outCharset=utf-8&format=xml"}
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:361)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.alibaba.fastjson.JSONArray.getJSONObject(JSONArray.java:244)
        at com.ejlchina.data.fastjson.FastjsonArray.getMapper(FastjsonArray.java:28)
        at com.sqmusicplus.plug.qqvip.entity.QQVipSearchEntity.songInfoToMusic(QQVipSearchEntity.java:48)
        at com.sqmusicplus.plug.qq.hander.QQHander.querySongById(QQHander.java:112)
        at com.sqmusicplus.plug.base.hander.SearchHanderAbstract.dnonloadAndSaveToFile(SearchHanderAbstract.java:44)
        at com.sqmusicplus.download.DownloadExcute.lambda$getDownloadInfo$0(DownloadExcute.java:90)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
[Fatal Error] :1:1: Content is not allowed in prolog.
[Fatal Error] :1:1: Content is not allowed in prolog.
14:03:19.931 [threadPoolTaskExecutor-20] INFO  c.s.u.DownloadUtils - [lambda$getHttp$0,81] - 超时重试第0次！
14:03:19.932 [threadPoolTaskExecutor-20] INFO  c.s.u.DownloadUtils - [lambda$getHttp$0,81] - 超时重试第1次！
14:03:19.932 [threadPoolTaskExecutor-20] INFO  c.s.u.DownloadUtils - [lambda$getHttp$0,81] - 超时重试第2次！
14:03:19.933 [threadPoolTaskExecutor-20] ERROR c.s.u.DownloadUtils - [lambda$getHttp$0,78] - 多次请求失败！：http://gcsp.kzti.top:1030/client/cgi-bin/api.fcg
java.lang.RuntimeException: 多次请求失败:http://gcsp.kzti.top:1030/client/cgi-bin/api.fcg
        at com.sqmusicplus.utils.DownloadUtils.lambda$getHttp$0(DownloadUtils.java:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at com.ejlchina.okhttps.SHttpTask.lambda$request$0(SHttpTask.java:102)
        at com.ejlchina.okhttps.internal.AbstractHttpClient.preprocess(AbstractHttpClient.java:184)
        at com.ejlchina.okhttps.SHttpTask.request(SHttpTask.java:92)
        at com.ejlchina.okhttps.SHttpTask.post(SHttpTask.java:51)
        at com.sqmusicplus.plug.qq.hander.QQHander.getDownloadUrl(QQHander.java:233)
        at com.sqmusicplus.plug.base.hander.SearchHanderAbstract.dnonloadAndSaveToFile(SearchHanderAbstract.java:67)
        at com.sqmusicplus.download.DownloadExcute.lambda$getDownloadInfo$0(DownloadExcute.java:90)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
java.lang.RuntimeException: 下载失败:I Lomo You
        at com.sqmusicplus.plug.base.hander.SearchHanderAbstract.dnonloadAndSaveToFile(SearchHanderAbstract.java:185)
        at com.sqmusicplus.download.DownloadExcute.lambda$getDownloadInfo$0(DownloadExcute.java:90)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by 59799517** [comment]
免费的话试试 酷我+ freeMP3插件下载 基本能覆盖全部歌了    目前使用的是落雪的下载接口  ikun公益音源：[https://lxmusic.ikunshare.com:9763/script?key=ikunsource音源作者https://github.com/ikun0014/](https://lxmusic.ikunshare.com:9763/script?key=ikunsource%E9%9F%B3%E6%BA%90%E4%BD%9C%E8%80%85https://github.com/ikun0014/)  这个有flac音源如果 对音质没要求的话可以试试其他的落雪音源 其他的最大也就320
